# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

# Adapt as necessary starting from here

## https://github.com/krlmlr/r-appveyor/issues/34
## http://stackoverflow.com/questions/33411765/check-multiple-subdirectories-using-appveyor

environment:
  global:
    TEST_DIR: OncoSimulR
    USE_RTOOLS: true
    R_BUILD_ARGS: --keep-empty-dirs --no-resave-data --no-manual
    R_CHECK_ARGS: --timings --no-vignettes --no-manual 
## --no-manual and forward because they are needed for appveyor
## --install-args=--build --no-multiarch
## R_VERSION: depending on BioC version, it has to bee devel or patched (or stable)    
  matrix:
   - R_VERSION: patched
     R_ARCH: x64
     GCC_PATH: mingw_64
        
   - R_VERSION: patched
     R_ARCH: i386
     GCC_PATH: mingw_32
     
###
##   - R_ARCH: x64
##     GCC_PATH: mingw_64
##     RTOOLS_VERSION: 33
##     R_VERSION: devel
      
##   - R_ARCH: i386
##     GCC_PATH: mingw_32
##     RTOOLS_VERSION: 33
##     R_VERSION: devel
     
     
    ## - R_ARCH: x64
    ##   GCC_PATH: mingw_64
    ##   RTOOLS_VERSION: 33
    ##   R_VERSION: release
      
    ## - R_ARCH: i386
    ##   GCC_PATH: mingw_32
    ##   RTOOLS_VERSION: 33
    ##   R_VERSION: release

    ## - R_ARCH: x64
    ##   GCC_PATH: mingw_64
    ##   RTOOLS_VERSION: 33
    ##   R_VERSION: patched
      
    ## - R_ARCH: i386
    ##   GCC_PATH: mingw_32
    ##   RTOOLS_VERSION: 33
    ##   R_VERSION: patched


## No longer make any sense starting with R-3.3
## - RTOOLS_VERSION: 32
##   R_ARCH: i386
## - RTOOLS_VERSION: 32
##  R_ARCH: x64
    
## As soon as R-3.3 is new stable, and all migrated to Rtools 3.3
## we will remove the last two entries

## R_VERSION: 3.3.0alpha
##  GCC_PATH: gcc-4.6.3
##  R_ARCH: i386

##  R_VERSION: 3.3.0alpha

before_build:
   - cp ../travis-tool.sh travis-tool.sh
   - cp travis-tool.sh.cmd %TEST_DIR%\travis-tool.sh.cmd
   - cd %TEST_DIR%
   - bash -c "echo '^travis-tool\.sh\.cmd$' >> .Rbuildignore"
   
## Failing because gtable and scales not available, as seen in logs. 
## These are ggplot2 imports, so should work and did work. Oh well. 
## Make explicit. But I shouldn't need any line after install_bioc_deps
build_script:
  - travis-tool.sh install_bioc_deps
  - travis-tool.sh install_r data.table
##- travis-tool.sh install_bioc nem
##  - travis-tool.sh install_bioc BiocGenerics graph
##  - travis-tool.sh install_bioc BiocStyle Rgraphviz
##  - travis-tool.sh install_r Oncotree testthat pander data.table gtools igraph car dplyr smatr ggrepel
##  - travis-tool.sh install_r gtable lazyeval digest tibble reshape2 MASS
##  - travis-tool.sh install_r chron DBI lazyeval pbkrtest scales assetthat R6 
##  - travis-tool.sh install_r quantreg mgcv nnet magrittr NMF irlba Matrix
##   - travis-tool.sh install_bioc RBGL
  ## BioNet pulls RBGL dependency ?? joda does too. That is why bgmm lpSolv joda lpNet and BioNet are there
##  - travis-tool.sh install_bioc nem  ## lpNet (which depends on lpSolve) is there to pull the nem dependency
##    - travis-tool.sh install_r bgmm lpSolve
   
##- travis-tool.sh install_bioc_deps  ## not working in pre 3.5 in appveyor because repo
## does not exist. So I pass the two packages, BiocStyle and Rgraphviz explicitly

## I might not need these anymore? (which I never should have needed anyway)
## - travis-tool.sh install_r gtable
## - travis-tool.sh install_r scales
## - travis-tool.sh install_r chron dplyr DBI ggplot2 geforce ggraph data.table knitr testthat car pbkrtest smatr ggrepel RColorBrewer igraph graph gtools rmarkdown bookdown
## - travis-tool.sh install_bioc BiocGenerics BiocStyle Rgraphviz

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip
  - ps: Get-EventLog AppVeyor -newest 10 | Format-List

on_success:
  - 7z a success.zip *.Rcheck\*
  - appveyor PushArtifact success.zip
  

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
